# Week 4 Seminar Answers

## Question 1

In [1]:
print("Hello World!") # this is in a code cell

Hello World!


In [2]:
type("Hello World!")

str

## Question 2

Indentation

Python uses whitespace (tabs or spaces) to structure codes. Consider the following for loop:

In [3]:
for x in range(10): # a colon denotes the start of an indented block
    if x < 5: # Jupyter automatically indent by four spaces
        print(x)
    else:
        pass # do nothing

0
1
2
3
4


This statement won't work if we mess up with indentations, for example:

In [4]:
for x in range(10):
if x < 5:
print(x)
else:
pass

IndentationError: expected an indented block (<ipython-input-4-d6d12957d2e6>, line 2)

## Question 3

String to Numerical

Often when we need to import data from plain text files such as CSV, numerical data can be interpreted as strings. Thus we also needs to covert strings to numerical values

In [5]:
# to be able to do mathematical operations, we need to convert strings to numbers...
wrong_data = '100' # error if you do numerical opertion on a string type

right_data = int(wrong_data) # convert to float

print(right_data, type(right_data))

100 <class 'int'>


## Question 4

None is NoneType

In [6]:
value = None # True & False are special kinds of data
print(value, type(value))

None <class 'NoneType'>


## Question 5

Examples of Python built-in math functions

The round() function will round a number to a specified number of the decimal points (the default is 0).

In [7]:
x = -0.05

# the 1st and 2th argument is for how many decimals you need for the results
print(round(x), round(x, 1), round(x, 2))

0 -0.1 -0.05


## Question 6

input() function: read user (you)'s input

In [2]:
# create a variable store name
# input will return whatever input by user.
print("What's your name?")
my_name = input()
print("What's your age?")
# input function outputs string now
my_age = input()
print("Hello, my name is {} and I am {} years old!".format(my_name, my_age))

What's your name?
Yang
What's your age?
80
Hello, my name is Yang and I am 80 years old!


## Question 7

In [16]:
import numpy as np
#Method1:
x=np.matrix([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
print(x)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [22]:
#Method2: 
x2 = np.arange(1,17).reshape((4, 4))
print(x2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


## Question 8

In [17]:
sumx0=np.sum(x[0,:])
stdx1=np.std(x[:,1])
ele01=x[0,1]
print(sumx0)
print(stdx1)
print(ele01)

10
4.47213595499958
2


## Question 9 

In [18]:
x=np.zeros((3, 4))
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
